apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: timer
spec:
  flows:
    - route:
        from:
          uri: kamelet:aws-sqs-source
          steps:
            - process: {}
            - convertBodyTo: {}
          parameters:
            accessKey: r3@cti0n
          id: admin@localhost
