apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: Converter
spec:
  flows:
    - restConfiguration:
        scheme: http
        host: localhost
        port: '8090'
    - rest:
        post:
          - to: direct:ReceiveRequest
            consumes: application/xml
            path: /blob
        path: /data
    - route:
        from:
          uri: direct:ReceiveRequest
          steps:
            - sort:
                expression:
                  tokenize:
                    token: ','
                    includeTokens: false
            - convertBodyTo:
                type: java.io.InputStream
            - log:
                message: ${body}
